AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/**/*'
    - 'config/environments/**/*'
    - 'config/initializers/devise.rb'
    - 'db/**/*'
    - 'vendor/**/*'

AccessModifierIndentation:
  EnforcedStyle: outdent

AlignHash:
  EnforcedHashRocketStyle: separator
  EnforcedColonStyle: separator

ClassAndModuleChildren:
  Enabled: false

CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Documentation:
  Enabled: false

EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

EndAlignment:
  AlignWith: variable

Encoding:
  EnforcedStyle: when_needed

IfUnlessModifier:
  MaxLineLength: 120

IndentationConsistency:
  Exclude:
    - '**/factories/**/*'

IndentationWidth:
  Exclude:
    - '**/factories/**/*'

LineLength:
  Max: 120

NonNilCheck:
  IncludeSemanticChanges: true

RaiseArgs:
  EnforcedStyle: compact

RedundantSelf:
  Exclude:
    - '**/models/**/*'

Semicolon:
  AllowAsExpressionSeparator: true

SpaceBeforeBlockBraces:
  EnforcedStyle: no_space

SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

SingleLineMethods:
  Enabled: false

WhileUntilModifier:
  MaxLineLength: 120

##################### Lint ##################################

EndAlignment:
  AlignWith: variable
