AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/AlignHash:
  EnforcedHashRocketStyle: separator
  EnforcedColonStyle: separator

Style/ClassAndModuleChildren:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/Documentation:
  Enabled: false

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/EndAlignment:
  AlignWith: variable

Style/Encoding:
  EnforcedStyle: when_needed

Style/IfUnlessModifier:
  MaxLineLength: 120

Style/IndentationConsistency:
  Exclude:
    - 'test/factories/**/*'

Style/IndentationWidth:
  Exclude:
    - 'test/factories/**/*'

Style/LineLength:
  Max: 120

Style/NonNilCheck:
  IncludeSemanticChanges: true

Style/RaiseArgs:
  EnforcedStyle: compact

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/SingleLineMethods:
  Enabled: false

Style/WhileUntilModifier:
  MaxLineLength: 120

##################### Lint ##################################

Lint/EndAlignment:
  AlignWith: variable
