development:
  admin_name: Admin User
  admin_email: admin@redsteel.com
  admin_password: changeme
  mandrill_username: <%= ENV['MANDRILL_USERNAME'] %>
  mandrill_apikey: <%= ENV['MANDRILL_APIKEY'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

test:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

production:
  admin_name: <%= ENV['ADMIN_NAME'] %>
  admin_email: <%= ENV['ADMIN_EMAIL'] %>
  admin_password: <%= ENV['ADMIN_PASSWORD'] %>
  mandrill_username: <%= ENV['MANDRILL_USERNAME'] %>
  mandrill_apikey: <%= ENV['MANDRILL_APIKEY'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
