development:
  admin_name: Admin User
  admin_email: admin@redsteel.com
  admin_password: changeme
  mandrill_username: <%= Duffel.mandrill_username %>
  mandrill_apikey: <%= Duffel.mandrill_apikey %>
  secret_key_base: <%= Duffel.secret_key_base %>

test:
  secret_key_base: <%= Duffel.secret_key_base %>

production:
  admin_name: <%= Duffel.admin_name %>
  admin_email: <%= Duffel.admin_email %>
  admin_password: <%= Duffel.admin_password %>
  mandrill_username: <%= Duffel.mandrill_username %>
  mandrill_apikey: <%= Duffel.mandrill_apikey %>
  secret_key_base: <%= Duffel.secret_key_base %>
